version: '3'

services:
  appnode:
    container_name: appnode
    entrypoint: dockerize -wait tcp://dbnode:3306 -timeout 20s npm start
    image: andersonascimento/fullcycle-appnode
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    networks:
      - net1
    tty: true
    ports:
      - "3333:3333"
    depends_on:
      - dbnode

  dbnode:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: dbnode
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net1

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: andersonascimentoafsn/nginx
    container_name: nginxnode
    networks:
      - net1
    ports:
      - "8080:80"

networks:
  net1:
    driver: bridge